import "./autogenerated.css";
import { useFilterUserGuides } from "../../hooks";
import { ENDPOINT } from "../../common/endpoints";
import { LoadingSpinner, TeamFilter, Feed } from "../../components";

const AutoGenerated = () => {
  const { guides, searchQuery, setSearchQuery, setTraitFilter } = useFilterUserGuides(ENDPOINT.AUTO_GENERATED_GUIDE);

  const handleSetSearchQuery = (value: string) => {
    setSearchQuery(value);
  };

  const handleSetTraitFilter = (trait: string) => {
    setTraitFilter(trait === "all" ? null : trait);
  };

  return (
    <div className="app__autogenerated page_padding">
      <TeamFilter searchQuery={searchQuery} onQueryChange={handleSetSearchQuery} onTraitChange={handleSetTraitFilter} />
      {!guides ? <LoadingSpinner /> : !!guides.length && <Feed posts={guides} />}
    </div>
  );
};

export default AutoGenerated;
