using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TFT_API.Migrations
{
    /// <inheritdoc />
    public partial class Comments : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "GuideId",
                table: "Comments");

            migrationBuilder.AddColumn<int>(
                name: "AutoGeneratedGuideId",
                table: "Comments",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "UserGuideId",
                table: "Comments",
                type: "int",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Comments_AutoGeneratedGuideId",
                table: "Comments",
                column: "AutoGeneratedGuideId");

            migrationBuilder.CreateIndex(
                name: "IX_Comments_UserGuideId",
                table: "Comments",
                column: "UserGuideId");

            migrationBuilder.AddForeignKey(
                name: "FK_Comments_AutoGeneratedGuides_AutoGeneratedGuideId",
                table: "Comments",
                column: "AutoGeneratedGuideId",
                principalTable: "AutoGeneratedGuides",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Comments_UserGuides_UserGuideId",
                table: "Comments",
                column: "UserGuideId",
                principalTable: "UserGuides",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Comments_AutoGeneratedGuides_AutoGeneratedGuideId",
                table: "Comments");

            migrationBuilder.DropForeignKey(
                name: "FK_Comments_UserGuides_UserGuideId",
                table: "Comments");

            migrationBuilder.DropIndex(
                name: "IX_Comments_AutoGeneratedGuideId",
                table: "Comments");

            migrationBuilder.DropIndex(
                name: "IX_Comments_UserGuideId",
                table: "Comments");

            migrationBuilder.DropColumn(
                name: "AutoGeneratedGuideId",
                table: "Comments");

            migrationBuilder.DropColumn(
                name: "UserGuideId",
                table: "Comments");

            migrationBuilder.AddColumn<int>(
                name: "GuideId",
                table: "Comments",
                type: "int",
                nullable: false,
                defaultValue: 0);
        }
    }
}
