using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TFT_API.Interfaces;
using TFT_API.Models.UserGuides;
using TFT_API.Models.AutoGeneratedGuide;
using Microsoft.Extensions.Caching.Memory;
using System.Security.Claims;
using TFT_API.Filters;
using TFT_API.Models.FetchedTFTData;

namespace TFT_API.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    [ValidateRequestBody]
    public class GuideController(IGuideDataAccess userGuideRepo, IMapper mapper, IUserDataAccess userRepo) : ControllerBase
    {
        private readonly IGuideDataAccess _userGuideRepo = userGuideRepo;
        private readonly IMapper _mapper = mapper;
        private readonly IUserDataAccess _userRepo = userRepo;

        [AllowAnonymous]
        [HttpGet("type/{type}/{userId?}")]
        public async Task<ActionResult<List<FeedUserGuideDto>>> GetUserGuides(
            [FromRoute] string type,
            [FromRoute] int? userId)
        {
            var userGuides = await _userGuideRepo.GetUserGuidesAsync(type);
            if (userGuides == null || userGuides.Count == 0)
                return NotFound($"No guides found");
            if (userId.HasValue && userId > 0)
            {
                await AddUserVotes(userGuides, userId.Value);
            }
            return Ok(userGuides);
        }

        [Authorize]
        [HttpGet("user")]
        public async Task<ActionResult<List<FeedUserGuideDto>>> GetUserGuidesByUserId()
        {
            if (!int.TryParse(User.FindFirstValue("UserId"), out int userId)) 
                return Unauthorized("Invalid User ID.");
            var userGuides = await  _userGuideRepo.GetUserGuidesByUserIdAsync(userId);
            if (userGuides == null || userGuides.Count == 0)
                return NotFound($"No guides found with User ID.");
            await AddUserVotes(userGuides, userId);
            return Ok(userGuides);
        }

        [Authorize]
        [HttpGet("commented")]
        public async Task<ActionResult<List<FeedUserGuideDto>>> GetCommentedUserGuides()
        {
            if (!int.TryParse(User.FindFirstValue("UserId"), out int userId)) 
                return Unauthorized("Invalid User ID.");
            var userGuides = await _userGuideRepo.GetCommentedUserGuidesAsync(userId);
            if (userGuides == null || userGuides.Count == 0)
                return NotFound($"No commented guides found with User ID.");
            await AddUserVotes(userGuides, userId);
            return Ok(userGuides);
        }

        [Authorize]
        [HttpGet("upvoted")]
        public async Task<ActionResult<List<FeedUserGuideDto>>> GetUpvotedUserGuides()
        {
            if (!int.TryParse(User.FindFirstValue("UserId"), out int userId)) 
                return Unauthorized("Invalid User ID.");
            var userGuides = await _userGuideRepo.GetUpvotedUserGuidesAsync(userId);
            if (userGuides == null || userGuides.Count == 0)
                return NotFound($"No upvoted guides found with User ID.");
            await AddUserVotes(userGuides, userId);
            return Ok(userGuides);
        }

        [Authorize]
        [HttpGet("downvoted")]
        public async Task<ActionResult<List<FeedUserGuideDto>>> GetDownvotedUserGuides()
        {
            if (!int.TryParse(User.FindFirstValue("UserId"), out int userId)) 
                return Unauthorized("Invalid User ID.");
            var userGuides = await _userGuideRepo.GetDownvotedUserGuidesAsync(userId);
            if (userGuides == null || userGuides.Count == 0)
                return NotFound($"No downvoted guides found with User ID.");
            await AddUserVotes(userGuides, userId);
            return Ok(userGuides);
        }

        [AllowAnonymous]
        [HttpGet("{id}", Name = "GetUserGuide")]
        public async Task<ActionResult<UserGuideDto>> GetUserGuideById([FromRoute] int id)
        {
            var userGuide = await _userGuideRepo.GetUserGuideByIdAsync(id);
            if (userGuide == null) return NotFound($"User guide with ID {id} not found.");
            return Ok(userGuide);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult<UserGuideDto>> AddUserGuide([FromBody] UserGuideRequest request)
        {
            if (!int.TryParse(User.FindFirstValue("UserId"), out int userId))
                return Unauthorized("Invalid User ID.");
            var user = await _userRepo.GetUserByIdAsync(userId);
            if (user == null) return NotFound("User was not found.");
            var newUserGuide = _mapper.Map<UserGuide>(request);
            newUserGuide.UsersUsername = user.Username;
            newUserGuide.UserId = userId;
            newUserGuide.CreatedAt = DateTime.Now;
            newUserGuide.UpdatedAt = DateTime.Now;

            if (string.IsNullOrEmpty(newUserGuide.Stage2Desc) ||
                string.IsNullOrEmpty(newUserGuide.Stage3Desc) ||
                string.IsNullOrEmpty(newUserGuide.Stage4Desc) ||
                string.IsNullOrEmpty(newUserGuide.GeneralDesc) ||
                string.IsNullOrEmpty(newUserGuide.DifficultyLevel) ||
                string.IsNullOrEmpty(newUserGuide.PlayStyle))
            {
                newUserGuide.IsDraft = true;
            }

            var userGuideDto = await _userGuideRepo.AddUserGuideAsync(newUserGuide);

            user.GuidesCount++;
            await _userRepo.UpdateUserAsync(user);

            return CreatedAtRoute("GetUserGuide", new { id = userGuideDto.Id }, userGuideDto);
        }

        [Authorize]
        [HttpPut]
        public async Task<ActionResult<UserGuideDto>> UpdateUserGuide([FromBody] UserGuideDto userGuide)
        {
            if (!int.TryParse(User.FindFirstValue("UserId"), out int userId) || userId != userGuide.UserId)
                return Unauthorized("Invalid User ID or not authorized.");
            var currentUserGuide = await _userGuideRepo.GetFullUserGuideByIdAsync(userGuide.Id);
            if (currentUserGuide == null)
                return NotFound($"User guide with ID {userGuide.Id} not found.");
            try
            {
                currentUserGuide = _mapper.Map(userGuide, currentUserGuide);
                currentUserGuide.UpdatedAt = DateTime.Now;
                var userGuideDto = await _userGuideRepo.UpdateUserGuideAsync(currentUserGuide);
                return Ok(userGuideDto);
            }catch (Exception ex)
            {
                return BadRequest("Failed to modify the user guide. Error: " + ex.Message);
            }
        }

        [Authorize]
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteUserGuide([FromRoute] int id)
        {
            if (!int.TryParse(User.FindFirstValue("UserId"), out int userId))
                return Unauthorized("Invalid User ID.");
            var userGuide = await _userGuideRepo.GetFullUserGuideByIdAsync(id);
            if (userGuide == null)
                return NotFound($"User guide with ID {id} not found.");
            if (userId != userGuide.UserId)
                return Unauthorized("Not authorized to delete this guide.");
            await _userGuideRepo.DeleteUserGuideAsync(id);
            return NoContent();
        }

        [AllowAnonymous]
        [HttpGet("autogenerated/{userId?}")]
        public async Task<ActionResult<List<AutoGeneratedGuideDto>>> GetAutoGeneratedGuides([FromRoute] int? userId)
        {
            var autoGeneratedGuides = await _userGuideRepo.GetAutoGeneratedGuidesAsync();
            if (autoGeneratedGuides == null || autoGeneratedGuides.Count == 0)
                return NotFound("No auto-generated guides found.");
            if (userId.HasValue && userId > 0)
            {
                await AddUserVotes(autoGeneratedGuides, userId.Value);
            }
            return Ok(autoGeneratedGuides);
        }

        private async Task AddUserVotes<T>(List<T> guides, int userId) where T : IGuideDto
        {
            var userVotes = await _userGuideRepo.GetUserVotesAsync(userId);

            foreach (var guide in guides)
            {
                if (userVotes.TryGetValue(guide.Id, out bool value))
                {
                    guide.IsUpvote = value;
                }
                else
                {
                    guide.IsUpvote = null;
                }
            }
        }
    }   
}
