import { Route, BrowserRouter, Routes } from "react-router-dom";
import { WindowDimensionsProvider, AuthProvider } from "./context";
import { MainLayout, AuthLayout } from "./layouts";
import {
  AugmentsStats,
  UnitsStats,
  CompsStats,
  Home,
  ItemsStats,
  MyTeamComps,
  TeamBuilder,
  AutoGenerated,
  TraitsStats,
  UnitDetails,
  AugmentDetails,
  ItemDetails,
  TraitDetails,
  Login,
  Register,
  MyPage,
  ViewGuide,
  OddsOfHitting,
  EditProfile,
} from "./pages";
import "./App.css";
import { Provider } from "react-redux";
import store from "./store";

function AppRouter() {
  return (
    <Routes>
      <Route path="/" element={<AuthLayout />}>
        <Route path="/sign-in" element={<Login />} />
        <Route path="/register" element={<Register />} />
      </Route>
      <Route path="/" element={<MainLayout />}>
        <Route index element={<Home />} />
        <Route path="/odds-of-hitting" element={<OddsOfHitting />} />
        <Route path="/auto-generated" element={<AutoGenerated />} />
        <Route path="/my-team-comps" element={<MyTeamComps />} />
        <Route path="/team-builder" element={<TeamBuilder />} />
        <Route path="/unit-stats" element={<UnitsStats />} />
        <Route path="/comp-stats" element={<CompsStats />} />
        <Route path="/augment-stats" element={<AugmentsStats />} />
        <Route path="/item-stats" element={<ItemsStats />} />
        <Route path="/trait-stats" element={<TraitsStats />} />
        <Route path="/my-page" element={<MyPage />} />
        <Route path="/guide/:guideId" element={<ViewGuide />} />
        <Route path="/unit-details" element={<UnitDetails />} />
        <Route path="/augment-details" element={<AugmentDetails />} />
        <Route path="/item-details" element={<ItemDetails />} />
        <Route path="/trait-details" element={<TraitDetails />} />
        <Route path="/edit-profile" element={<EditProfile />} />
      </Route>
    </Routes>
  );
}

function App() {
  return (
    <Provider store={store}>
      <BrowserRouter>
        <AuthProvider>
          <WindowDimensionsProvider>
            <AppRouter />
          </WindowDimensionsProvider>
        </AuthProvider>
      </BrowserRouter>
    </Provider>
  );
}

export default App;
