using TFT_API.Models.UserGuides;
using TFT_API.Interfaces;


namespace TFT_API.Models.AutoGeneratedGuide
{
    public class AutoGeneratedGuideDto : IGuideDto
    {
        public int Id { get; set; }
        public GuideUnitDto InitialUnit { get; set; } = new GuideUnitDto();
        public int UpVotes { get; set; }
        public int DownVotes { get; set; }
        public int Views { get; set; }
        public string Patch { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public string Stage2Desc { get; set; } = string.Empty;
        public string Stage3Desc { get; set; } = string.Empty;
        public string Stage4Desc { get; set; } = string.Empty;
        public string GeneralDesc { get; set; } = string.Empty;
        public string DifficultyLevel { get; set; } = string.Empty;
        public string PlayStyle { get; set; } = string.Empty;
        public List<HexDto> Hexes { get; set; } = [];
        public List<PartialGuideTraitDto> Traits { get; set; } = [];
        public List<GuideAugmentDto> Augments { get; set; } = [];
        public bool? IsUpvote { get; set; }
    }
}
