using TFT_API.Models.AutoGeneratedGuide;
using TFT_API.Models.UserGuides;
using TFT_API.Models.Votes;

namespace TFT_API.Interfaces
{
    public interface IGuideDataAccess
    {
        Task<List<FeedUserGuideDto>> GetUserGuidesAsync(string sortBy);
        Task<UserGuideDto> AddUserGuideAsync(UserGuide userGuide);
        Task<UserGuide?> GetFullUserGuideByIdAsync(int id);
        Task<UserGuideDto?> GetUserGuideByIdAsync(int id);
        Task<List<FeedUserGuideDto>> GetUserGuidesByUserIdAsync(int id);
        Task<List<FeedUserGuideDto>> GetCommentedUserGuidesAsync(int id);
        Task<List<FeedUserGuideDto>> GetUpvotedUserGuidesAsync(int id);
        Task<List<FeedUserGuideDto>> GetDownvotedUserGuidesAsync(int id);
        Task<UserGuideDto?> UpdateUserGuideAsync(UserGuide userGuide);
        Task DeleteUserGuideAsync(int id);
        Task<List<AutoGeneratedGuideDto>> GetAutoGeneratedGuidesAsync();
        Task<Dictionary<int, bool>> GetUserVotesAsync(int userId);
    }
}
