using TFT_API.Models.AutoGeneratedGuide;
using TFT_API.Models.Item;
using TFT_API.Models.User;
using TFT_API.Models.UserGuides;
using TFT_API.Models.Votes;

namespace TFT_API.Interfaces
{
    public interface IGuideDataAccess
    {
        List<UserGuide> GetUserGuides(string sortBy);
        UserGuide AddUserGuide(UserGuide userGuide);
        UserGuide? GetUserGuideById(int id);
        List<UserGuide> GetUserGuidesByUserId(int id);
        List<UserGuide> GetCommentedUserGuides(int id);
        List<UserGuide> GetUpvotedUserGuides(int id);
        List<UserGuide> GetDownvotedUserGuides(int id);
        UserGuide? UpdateUserGuide(UserGuide userGuide);
        void DeleteUserGuide(int id);
        List<UserGuide> GetAutoGeneratedGuides();
        List<Vote> GetUserVotes(int userId);
    }
}
